ArrayOperationsTester.out: ArrayOperationsTester.cpp ArrayOperations.h ArrayOperations.cpp
	g++ ArrayOperationsTester.cpp ArrayOperations.h ArrayOperations.cpp -o ArrayOperationsTester.out

test: ArrayOperationsTester.out
	./ArrayOperationsTester.out
